pull_request_rules:
  - name: Automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/push
      - status-success=codecov/patch
    actions:
      merge:
        method: merge
        strict: smart
      delete_head_branch:
